name: Daily Backup

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 */8 * *'

jobs:
  backup:
    runs-on: ubuntu-latest
    
    env:
      TWIKOO_PASSWORD: ${{ secrets.TWIKOO_PASSWORD }}
      TWIKOO_URL: ${{ secrets.TWIKOO_URL }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install
      
    - name: Create backup directory if it does not exist
      run: mkdir -p backup
      
    - name: Run backup script
      run: node index.js
    
      
    - name: Delete backups older than 30 days
      run: find backup -name 'twikoo-comment-*.json' -mtime +30 -exec rm {} \;

    - name: Replace existing backups if the same
      run: |
        for file in twikoo-comment-*.json; do
          [ -e "$file" ] || continue
          if [ -f "backup/$file" ] && cmp -s "$file" "backup/$file"; then
            mv "$file" "backup/$file"
          else
            mv "$file" "backup/"
          fi
        done

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add backup/*.json
        git commit -m 'Daily backup'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}